changelog:
  exclude:
    labels:
      - release-ignore
  categories:
    - title: Breaking Changes 🛠
      labels:
        - release-MAJOR
    - title: New Features 🎉
      labels:
        - release-MINOR
    - title: Other Changes & Fixes
      labels:
        - release-PATCH
