changelog:
  exclude:
    labels:
      - release-IGNORE
  categories:
    - title: Breaking Changes 🛠
      labels:
        - 'Semver: MAJOR'
    - title: New Features 🎉
      labels:
        - 'Semver: MINOR'
    - title: Bug Fixes 🐛
      labels:
        - 'Semver: PATCH'
