
name: Bump version

# Based on: https://github.blog/2021-12-16-5-automations-every-developer-should-be-running/

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    # Check out the content (source branch).  Use a deploy key so that
    # when we push changes, it will trigger the release workflow
    # run that runs on: tag. (Using the GitHub token would
    # not run the workflow to prevent infinite recursion.)
    - name: Check out source
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup Git
      run: |
        git config user.name 'release-bot'
        git config user.email 'adamtuttlecodes@gmail.com'

    - name: bump version
      run: npm version ${{ github.event.inputs.version }}

    - name: Push latest version
      run: git push origin main --follow-tags

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Create Release Notes
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          await github.request(`POST /repos/${{ github.repository }}/releases`, {
            tag_name: "${{ steps.package-version.outputs.current-version}}",
            generate_release_notes: true
          });
